#!/usr/bin/env tsx

/**
 * Скрипт для импорта существующих маппингов из базы данных
 */
import { PrismaClient, GameType } from '@prisma/client'

const prisma = new PrismaClient()

// Все существующие маппинги из базы данных
const existingMappings = [
// === HSR ПРЕДМЕТЫ ===
  // Characters
  { englishName: 'a-secret-vow', russianName: 'Тайная клятва', game: 'HSR', itemType: 'Character', rarity: 5 },
  { englishName: 'acheron', russianName: 'Ахерон', game: 'HSR', itemType: 'Character', rarity: 5 },
  { englishName: 'adversarial', russianName: 'Противоборство', game: 'HSR', itemType: 'Character', rarity: 5 },
  { englishName: 'amber', russianName: 'Янтарь', game: 'HSR', itemType: 'Character', rarity: 5 },
  { englishName: 'argenti', russianName: 'Аргенти', game: 'HSR', itemType: 'Character', rarity: 5 },
  { englishName: 'arlan', russianName: 'Арлан', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'arrows', russianName: 'Стрелы', game: 'HSR', itemType: 'Character', rarity: 5 },
  { englishName: 'asta', russianName: 'Аста', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'bailu', russianName: 'Байлу', game: 'HSR', itemType: 'Character', rarity: 5 },
  { englishName: 'black-swan', russianName: 'Чёрный лебедь', game: 'HSR', itemType: 'Character', rarity: 5 },
  { englishName: 'bronya', russianName: 'Броня', game: 'HSR', itemType: 'Character', rarity: 5 },
  { englishName: 'castorice', russianName: 'Касторес', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'chorus', russianName: 'Хор', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'collapsing-sky', russianName: 'Обрушившееся небо', game: 'HSR', itemType: 'Character', rarity: 5 },
  { englishName: 'concert-for-two', russianName: 'Концерт на двоих', game: 'HSR', itemType: 'Character', rarity: 5 },
  { englishName: 'cornucopia', russianName: 'Рог изобилия', game: 'HSR', itemType: 'Character', rarity: 5 },
  { englishName: 'dan-heng', russianName: 'Дань Хэн', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'dan-heng-imbibitor-lunae', russianName: 'Дань Хэн - Имбибитор Лунае', game: 'HSR', itemType: 'Character', rarity: 5 },
  { englishName: 'dance-dance-dance', russianName: 'Танец-танец-танец', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'darting-arrow', russianName: 'Стремительная стрела', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'data-bank', russianName: 'Банк данных', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'day-one-of-my-new-life', russianName: 'Первый день моей новой жизни', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'defense', russianName: 'Защита', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'dreams-montage', russianName: 'Монтаж мечты', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'fine-fruit', russianName: 'Хороший фрукт', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'gallagher', russianName: 'Галлахер', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'geniuses-repose', russianName: 'Покой гениев', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'gepard', russianName: 'Гепард', game: 'HSR', itemType: 'Character', rarity: 5 },
  { englishName: 'good-night-and-sleep-well', russianName: 'Спокойной ночи и сладких снов', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'guinaifen', russianName: 'Гуйнайфэнь', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'hanya', russianName: 'Ханя', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'herta', russianName: 'Герта', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'hidden-shadow', russianName: 'Скрытая тень', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'hook', russianName: 'Крюк', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'jiaoqiu', russianName: 'Цзяоцю', game: 'HSR', itemType: 'Character', rarity: 5 },
  { englishName: 'jingliu', russianName: 'Цзинлю', game: 'HSR', itemType: 'Character', rarity: 5 },
  { englishName: 'kafka', russianName: 'Кафка', game: 'HSR', itemType: 'Character', rarity: 5 },
  { englishName: 'landaus-choice', russianName: 'Выбор Ландау', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'loop', russianName: 'Петля', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'luka', russianName: 'Лука', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'luocha', russianName: 'Лоча', game: 'HSR', itemType: 'Character', rarity: 5 },
  { englishName: 'lynx', russianName: 'Рысь', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'make-the-world-clamor', russianName: 'Заставить мир шуметь', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'march-7th', russianName: 'Март 7-го', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'mediation', russianName: 'Посредничество', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'meshing-cogs', russianName: 'Сцепляющиеся шестерёнки', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'misha', russianName: 'Миша', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'moze', russianName: 'Моцзэ', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'multiplication', russianName: 'Умножение', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'mutual-demise', russianName: 'Взаимная гибель', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'mydei', russianName: 'Майдэй', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'natasha', russianName: 'Наташа', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'only-silence-remains', russianName: 'Остаётся только тишина', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'passkey', russianName: 'Пропуск', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'pela', russianName: 'Пела', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'phainon', russianName: 'Фэйнон', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'pioneering', russianName: 'Пионерство', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'planetary-rendezvous', russianName: 'Планетарное свидание', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'poised-to-bloom', russianName: 'Готовый расцвести', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'post-op-conversation', russianName: 'Послеоперационный разговор', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'qingque', russianName: 'Цинцюэ', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'reminiscence', russianName: 'Воспоминание', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'resolution-shines-as-pearls-of-sweat', russianName: 'Решимость блестит как жемчужины пота', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'sagacity', russianName: 'Мудрость', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'sampo', russianName: 'Сампо', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'serval', russianName: 'Сервал', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'shadowburn', russianName: 'Ожог тени', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'shadowed-by-night', russianName: 'Затенённый ночью', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'shared-feeling', russianName: 'Общее чувство', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'shattered-home', russianName: 'Разбитый дом', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'subscribe-for-more', russianName: 'Подпишись за больше', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'sunday', russianName: 'Воскресенье', game: 'HSR', itemType: 'Character', rarity: 5 },
  { englishName: 'sushang', russianName: 'Сушан', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'swordplay', russianName: 'Фехтование', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'the-birth-of-the-self', russianName: 'Рождение себя', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'the-moles-welcome-you', russianName: 'Кроты приветствуют вас', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'tingyun', russianName: 'Тинъюнь', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'topaz-numby', russianName: 'Топаз и Намби', game: 'HSR', itemType: 'Character', rarity: 5 },
  { englishName: 'trend-of-the-universal-market', russianName: 'Тренд универсального рынка', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'tribbie', russianName: 'Трибби', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'under-the-blue-sky', russianName: 'Под голубым небом', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'void', russianName: 'Пустота', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'xueyi', russianName: 'Сюэи', game: 'HSR', itemType: 'Character', rarity: 4 },
  { englishName: 'yukong', russianName: 'Юконг', game: 'HSR', itemType: 'Character', rarity: 4 },

  // Light Cones
  { englishName: 'a-secret-vow', russianName: 'Тайная клятва', game: 'HSR', itemType: 'Light Cone', rarity: 4 },
  { englishName: 'adversarial', russianName: 'Противоборство', game: 'HSR', itemType: 'Light Cone', rarity: 3 },
  { englishName: 'after-the-charmony-fall', russianName: 'После падения гармонии', game: 'HSR', itemType: 'Light Cone', rarity: 4 },
  { englishName: 'amber', russianName: 'Янтарь', game: 'HSR', itemType: 'Light Cone', rarity: 3 },
  { englishName: 'arlan', russianName: 'Арлан', game: 'HSR', itemType: 'Light Cone', rarity: 4 },
  { englishName: 'arrows', russianName: 'Стрелы', game: 'HSR', itemType: 'Light Cone', rarity: 3 },
  { englishName: 'asta', russianName: 'Аста', game: 'HSR', itemType: 'Light Cone', rarity: 4 },
  { englishName: 'boundless-choreo', russianName: 'Безграничная хореография', game: 'HSR', itemType: 'Light Cone', rarity: 4 },
  { englishName: 'bronya', russianName: 'Броня', game: 'HSR', itemType: 'Light Cone', rarity: 5 },
  { englishName: 'chorus', russianName: 'Хор', game: 'HSR', itemType: 'Light Cone', rarity: 3 },
  { englishName: 'clara', russianName: 'Клара', game: 'HSR', itemType: 'Light Cone', rarity: 5 },
  { englishName: 'collapsing-sky', russianName: 'Обрушившееся небо', game: 'HSR', itemType: 'Light Cone', rarity: 3 },
  { englishName: 'concert-for-two', russianName: 'Концерт на двоих', game: 'HSR', itemType: 'Light Cone', rarity: 4 },
  { englishName: 'cornucopia', russianName: 'Рог изобилия', game: 'HSR', itemType: 'Light Cone', rarity: 3 },
  { englishName: 'dan-heng', russianName: 'Дань Хэн', game: 'HSR', itemType: 'Light Cone', rarity: 4 },
  { englishName: 'dance-dance-dance', russianName: 'Танец-танец-танец', game: 'HSR', itemType: 'Light Cone', rarity: 4 },
  { englishName: 'darting-arrow', russianName: 'Стремительная стрела', game: 'HSR', itemType: 'Light Cone', rarity: 3 },
  { englishName: 'data-bank', russianName: 'Банк данных', game: 'HSR', itemType: 'Light Cone', rarity: 3 },
  { englishName: 'day-one-of-my-new-life', russianName: 'Первый день моей новой жизни', game: 'HSR', itemType: 'Light Cone', rarity: 4 },
  { englishName: 'defense', russianName: 'Защита', game: 'HSR', itemType: 'Light Cone', rarity: 3 },
  { englishName: 'eyes-of-the-prey', russianName: 'Глаза добычи', game: 'HSR', itemType: 'Light Cone', rarity: 4 },
  { englishName: 'fine-fruit', russianName: 'Хороший фрукт', game: 'HSR', itemType: 'Light Cone', rarity: 3 },
  { englishName: 'flame-of-blood-blaze-my-path', russianName: 'Пламя крови - освети мой путь', game: 'HSR', itemType: 'Light Cone', rarity: 5 },
  { englishName: 'gallagher', russianName: 'Галлахер', game: 'HSR', itemType: 'Light Cone', rarity: 4 },
  { englishName: 'geniuses-greetings', russianName: 'Приветствие гениев', game: 'HSR', itemType: 'Light Cone', rarity: 4 },
  { englishName: 'geniuses-repose', russianName: 'Покой гениев', game: 'HSR', itemType: 'Light Cone', rarity: 4 },
  { englishName: 'gepard', russianName: 'Гепард', game: 'HSR', itemType: 'Light Cone', rarity: 5 },
  { englishName: 'good-night-and-sleep-well', russianName: 'Спокойной ночи и сладких снов', game: 'HSR', itemType: 'Light Cone', rarity: 4 },
  { englishName: 'guinaifen', russianName: 'Гуйнайфэнь', game: 'HSR', itemType: 'Light Cone', rarity: 4 },
  { englishName: 'hanya', russianName: 'Ханя', game: 'HSR', itemType: 'Light Cone', rarity: 4 },
  { englishName: 'herta', russianName: 'Герта', game: 'HSR', itemType: 'Light Cone', rarity: 4 },
  { englishName: 'hidden-shadow', russianName: 'Скрытая тень', game: 'HSR', itemType: 'Light Cone', rarity: 3 },
  { englishName: 'himeko', russianName: 'Химеко', game: 'HSR', itemType: 'Light Cone', rarity: 5 },
  { englishName: 'i-shall-be-my-own-sword', russianName: 'Я буду своим собственным мечом', game: 'HSR', itemType: 'Light Cone', rarity: 5 },
  { englishName: 'in-the-name-of-the-world', russianName: 'Во имя мира', game: 'HSR', itemType: 'Light Cone', rarity: 5 },
  { englishName: 'into-the-unreachable-veil', russianName: 'В недостижимую завесу', game: 'HSR', itemType: 'Light Cone', rarity: 5 },
  { englishName: 'landaus-choice', russianName: 'Выбор Ландау', game: 'HSR', itemType: 'Light Cone', rarity: 4 },
  { englishName: 'loop', russianName: 'Петля', game: 'HSR', itemType: 'Light Cone', rarity: 3 },
  { englishName: 'luka', russianName: 'Лука', game: 'HSR', itemType: 'Light Cone', rarity: 4 },
  { englishName: 'make-the-world-clamor', russianName: 'Заставить мир шуметь', game: 'HSR', itemType: 'Light Cone', rarity: 4 },
  { englishName: 'march-7th', russianName: 'Март 7-го', game: 'HSR', itemType: 'Light Cone', rarity: 4 },
  { englishName: 'mediation', russianName: 'Посредничество', game: 'HSR', itemType: 'Light Cone', rarity: 3 },
  { englishName: 'memories-of-the-past', russianName: 'Воспоминания о прошлом', game: 'HSR', itemType: 'Light Cone', rarity: 4 },
  { englishName: 'meshing-cogs', russianName: 'Сцепляющиеся шестерёнки', game: 'HSR', itemType: 'Light Cone', rarity: 3 },
  { englishName: 'misha', russianName: 'Миша', game: 'HSR', itemType: 'Light Cone', rarity: 4 },
  { englishName: 'moment-of-victory', russianName: 'Момент победы', game: 'HSR', itemType: 'Light Cone', rarity: 5 },
  { englishName: 'multiplication', russianName: 'Умножение', game: 'HSR', itemType: 'Light Cone', rarity: 3 },
  { englishName: 'mutual-demise', russianName: 'Взаимная гибель', game: 'HSR', itemType: 'Light Cone', rarity: 3 },
  { englishName: 'natasha', russianName: 'Наташа', game: 'HSR', itemType: 'Light Cone', rarity: 4 },
  { englishName: 'night-on-the-milky-way', russianName: 'Ночь на Млечном Пути', game: 'HSR', itemType: 'Light Cone', rarity: 5 },
  { englishName: 'only-silence-remains', russianName: 'Остаётся только тишина', game: 'HSR', itemType: 'Light Cone', rarity: 4 },
  { englishName: 'passkey', russianName: 'Пропуск', game: 'HSR', itemType: 'Light Cone', rarity: 3 },
  { englishName: 'pela', russianName: 'Пела', game: 'HSR', itemType: 'Light Cone', rarity: 4 },
  { englishName: 'perfect-timing', russianName: 'Идеальное время', game: 'HSR', itemType: 'Light Cone', rarity: 4 },
  { englishName: 'pioneering', russianName: 'Пионерство', game: 'HSR', itemType: 'Light Cone', rarity: 3 },
  { englishName: 'planetary-rendezvous', russianName: 'Планетарное свидание', game: 'HSR', itemType: 'Light Cone', rarity: 4 },
  { englishName: 'poised-to-bloom', russianName: 'Готовый расцвести', game: 'HSR', itemType: 'Light Cone', rarity: 4 },
  { englishName: 'post-op-conversation', russianName: 'Послеоперационный разговор', game: 'HSR', itemType: 'Light Cone', rarity: 4 },
  { englishName: 'qingque', russianName: 'Цинцюэ', game: 'HSR', itemType: 'Light Cone', rarity: 4 },
  { englishName: 'reminiscence', russianName: 'Воспоминание', game: 'HSR', itemType: 'Light Cone', rarity: 3 },
  { englishName: 'resolution-shines-as-pearls-of-sweat', russianName: 'Решимость блестит как жемчужины пота', game: 'HSR', itemType: 'Light Cone', rarity: 4 },
  { englishName: 'sagacity', russianName: 'Мудрость', game: 'HSR', itemType: 'Light Cone', rarity: 3 },
  { englishName: 'sampo', russianName: 'Сампо', game: 'HSR', itemType: 'Light Cone', rarity: 4 },
  { englishName: 'serval', russianName: 'Сервал', game: 'HSR', itemType: 'Light Cone', rarity: 4 },
  { englishName: 'shadowburn', russianName: 'Ожог тени', game: 'HSR', itemType: 'Light Cone', rarity: 3 },
  { englishName: 'shadowed-by-night', russianName: 'Затенённый ночью', game: 'HSR', itemType: 'Light Cone', rarity: 4 },
  { englishName: 'shared-feeling', russianName: 'Общее чувство', game: 'HSR', itemType: 'Light Cone', rarity: 4 },
  { englishName: 'shattered-home', russianName: 'Разбитый дом', game: 'HSR', itemType: 'Light Cone', rarity: 3 },
  { englishName: 'sleep-like-the-dead', russianName: 'Спать как мёртвый', game: 'HSR', itemType: 'Light Cone', rarity: 5 },
  { englishName: 'something-irreplaceable', russianName: 'Что-то незаменимое', game: 'HSR', itemType: 'Light Cone', rarity: 5 },
  { englishName: 'subscribe-for-more', russianName: 'Подпишись за больше', game: 'HSR', itemType: 'Light Cone', rarity: 4 },
  { englishName: 'sushang', russianName: 'Сушан', game: 'HSR', itemType: 'Light Cone', rarity: 4 },
  { englishName: 'swordplay', russianName: 'Фехтование', game: 'HSR', itemType: 'Light Cone', rarity: 4 },
  { englishName: 'the-birth-of-the-self', russianName: 'Рождение себя', game: 'HSR', itemType: 'Light Cone', rarity: 4 },
  { englishName: 'the-moles-welcome-you', russianName: 'Кроты приветствуют вас', game: 'HSR', itemType: 'Light Cone', rarity: 4 },
  { englishName: 'the-storys-next-page', russianName: 'Следующая страница истории', game: 'HSR', itemType: 'Light Cone', rarity: 4 },
  { englishName: 'those-many-springs', russianName: 'Те многие весны', game: 'HSR', itemType: 'Light Cone', rarity: 5 },
  { englishName: 'thus-burns-the-dawn', russianName: 'Так горит заря', game: 'HSR', itemType: 'Light Cone', rarity: 5 },
  { englishName: 'time-waits-for-no-one', russianName: 'Время никого не ждёт', game: 'HSR', itemType: 'Light Cone', rarity: 5 },
  { englishName: 'tingyun', russianName: 'Тинъюнь', game: 'HSR', itemType: 'Light Cone', rarity: 4 },
  { englishName: 'trend-of-the-universal-market', russianName: 'Тренд универсального рынка', game: 'HSR', itemType: 'Light Cone', rarity: 4 },
  { englishName: 'under-the-blue-sky', russianName: 'Под голубым небом', game: 'HSR', itemType: 'Light Cone', rarity: 4 },
  { englishName: 'void', russianName: 'Пустота', game: 'HSR', itemType: 'Light Cone', rarity: 3 },
  { englishName: 'why-does-the-ocean-sing', russianName: 'Почему поёт океан', game: 'HSR', itemType: 'Light Cone', rarity: 5 },
  { englishName: 'xueyi', russianName: 'Сюэи', game: 'HSR', itemType: 'Light Cone', rarity: 4 },
  { englishName: 'yanqing', russianName: 'Яньцин', game: 'HSR', itemType: 'Light Cone', rarity: 5 },
  { englishName: 'yukong', russianName: 'Юконг', game: 'HSR', itemType: 'Light Cone', rarity: 4 },

  // === GENSHIN ПРЕДМЕТЫ ===
  // Characters
  { englishName: 'albedo', russianName: 'Альбедо', game: 'GENSHIN', itemType: 'Character', rarity: 5 },
  { englishName: 'amber', russianName: 'Эмбер', game: 'GENSHIN', itemType: 'Character', rarity: 4 },
  { englishName: 'arataki itto', russianName: 'Аратаки Итто', game: 'GENSHIN', itemType: 'Character', rarity: 5 },
  { englishName: 'barbara', russianName: 'Барбара', game: 'GENSHIN', itemType: 'Character', rarity: 4 },
  { englishName: 'beidou', russianName: 'Бэй Доу', game: 'GENSHIN', itemType: 'Character', rarity: 4 },
  { englishName: 'bennett', russianName: 'Беннет', game: 'GENSHIN', itemType: 'Character', rarity: 4 },
  { englishName: 'candace', russianName: 'Кандакия', game: 'GENSHIN', itemType: 'Character', rarity: 4 },
  { englishName: 'charlotte', russianName: 'Шарлотта', game: 'GENSHIN', itemType: 'Character', rarity: 4 },
  { englishName: 'chasca', russianName: 'Часка', game: 'GENSHIN', itemType: 'Character', rarity: 5 },
  { englishName: 'chevreuse', russianName: 'Шеврёз', game: 'GENSHIN', itemType: 'Character', rarity: 4 },
  { englishName: 'chongyun', russianName: 'Чун Юнь', game: 'GENSHIN', itemType: 'Character', rarity: 4 },
  { englishName: 'collei', russianName: 'Коллеи', game: 'GENSHIN', itemType: 'Character', rarity: 4 },
  { englishName: 'dahlia', russianName: 'Далия', game: 'GENSHIN', itemType: 'Character', rarity: 5 },
  { englishName: 'dehya', russianName: 'Дэхья', game: 'GENSHIN', itemType: 'Character', rarity: 5 },
  { englishName: 'diluc', russianName: 'Дилюк', game: 'GENSHIN', itemType: 'Character', rarity: 5 },
  { englishName: 'diona', russianName: 'Диона', game: 'GENSHIN', itemType: 'Character', rarity: 4 },
  { englishName: 'dori', russianName: 'Дори', game: 'GENSHIN', itemType: 'Character', rarity: 4 },
  { englishName: 'faruzan', russianName: 'Фарузан', game: 'GENSHIN', itemType: 'Character', rarity: 4 },
  { englishName: 'fischl', russianName: 'Фишль', game: 'GENSHIN', itemType: 'Character', rarity: 4 },
  { englishName: 'freminet', russianName: 'Фремине', game: 'GENSHIN', itemType: 'Character', rarity: 4 },
  { englishName: 'furina', russianName: 'Фурина', game: 'GENSHIN', itemType: 'Character', rarity: 5 },
  { englishName: 'gaming', russianName: 'Гейминг', game: 'GENSHIN', itemType: 'Character', rarity: 4 },
  { englishName: 'gorou', russianName: 'Горо', game: 'GENSHIN', itemType: 'Character', rarity: 4 },
  { englishName: 'iansan', russianName: 'Янсан', game: 'GENSHIN', itemType: 'Character', rarity: 5 },
  { englishName: 'jean', russianName: 'Джинн', game: 'GENSHIN', itemType: 'Character', rarity: 5 },
  { englishName: 'kachina', russianName: 'Качина', game: 'GENSHIN', itemType: 'Character', rarity: 4 },
  { englishName: 'kaedehara kazuha', russianName: 'Каэдэхара Кадзуха', game: 'GENSHIN', itemType: 'Character', rarity: 5 },
  { englishName: 'kamisato ayaka', russianName: 'Камисато Аяка', game: 'GENSHIN', itemType: 'Character', rarity: 5 },
  { englishName: 'kamisato ayato', russianName: 'Камисато Аято', game: 'GENSHIN', itemType: 'Character', rarity: 5 },
  { englishName: 'kaveh', russianName: 'Кавех', game: 'GENSHIN', itemType: 'Character', rarity: 4 },
  { englishName: 'keqing', russianName: 'Кэ Цин', game: 'GENSHIN', itemType: 'Character', rarity: 5 },
  { englishName: 'kirara', russianName: 'Кирара', game: 'GENSHIN', itemType: 'Character', rarity: 4 },
  { englishName: 'kujou sara', russianName: 'Куджо Сара', game: 'GENSHIN', itemType: 'Character', rarity: 4 },
  { englishName: 'kuki shinobu', russianName: 'Куки Синобу', game: 'GENSHIN', itemType: 'Character', rarity: 4 },
  { englishName: 'layla', russianName: 'Лайла', game: 'GENSHIN', itemType: 'Character', rarity: 4 },
  { englishName: 'lisa', russianName: 'Лиза', game: 'GENSHIN', itemType: 'Character', rarity: 4 },
  { englishName: 'lynette', russianName: 'Линетт', game: 'GENSHIN', itemType: 'Character', rarity: 4 },
  { englishName: 'mika', russianName: 'Мика', game: 'GENSHIN', itemType: 'Character', rarity: 4 },
  { englishName: 'mona', russianName: 'Мона', game: 'GENSHIN', itemType: 'Character', rarity: 5 },
  { englishName: 'mualani', russianName: 'Муалани', game: 'GENSHIN', itemType: 'Character', rarity: 5 },
  { englishName: 'navia', russianName: 'Навия', game: 'GENSHIN', itemType: 'Character', rarity: 5 },
  { englishName: 'neuvillette', russianName: 'Невилетт', game: 'GENSHIN', itemType: 'Character', rarity: 5 },
  { englishName: 'ningguang', russianName: 'Нин Гуан', game: 'GENSHIN', itemType: 'Character', rarity: 4 },
  { englishName: 'noelle', russianName: 'Ноэлль', game: 'GENSHIN', itemType: 'Character', rarity: 4 },
  { englishName: 'ororon', russianName: 'Оророн', game: 'GENSHIN', itemType: 'Character', rarity: 5 },
  { englishName: 'qiqi', russianName: 'Ци Ци', game: 'GENSHIN', itemType: 'Character', rarity: 5 },
  { englishName: 'razor', russianName: 'Рэйзор', game: 'GENSHIN', itemType: 'Character', rarity: 4 },
  { englishName: 'rosaria', russianName: 'Розария', game: 'GENSHIN', itemType: 'Character', rarity: 4 },
  { englishName: 'sayu', russianName: 'Саю', game: 'GENSHIN', itemType: 'Character', rarity: 4 },
  { englishName: 'sethos', russianName: 'Сетос', game: 'GENSHIN', itemType: 'Character', rarity: 4 },
  { englishName: 'shenhe', russianName: 'Шэнь Хэ', game: 'GENSHIN', itemType: 'Character', rarity: 5 },
  { englishName: 'shikanoin heizou', russianName: 'Шикано-ин Хэйдзо', game: 'GENSHIN', itemType: 'Character', rarity: 4 },
  { englishName: 'sucrose', russianName: 'Сахароза', game: 'GENSHIN', itemType: 'Character', rarity: 4 },
  { englishName: 'thoma', russianName: 'Тома', game: 'GENSHIN', itemType: 'Character', rarity: 4 },
  { englishName: 'wriothesley', russianName: 'Ризли', game: 'GENSHIN', itemType: 'Character', rarity: 5 },
  { englishName: 'xiangling', russianName: 'Сян Лин', game: 'GENSHIN', itemType: 'Character', rarity: 4 },
  { englishName: 'xianyun', russianName: 'Сянь Юнь', game: 'GENSHIN', itemType: 'Character', rarity: 5 },
  { englishName: 'xilonen', russianName: 'Силонен', game: 'GENSHIN', itemType: 'Character', rarity: 5 },
  { englishName: 'xingqiu', russianName: 'Син Цю', game: 'GENSHIN', itemType: 'Character', rarity: 4 },
  { englishName: 'xinyan', russianName: 'Синь Янь', game: 'GENSHIN', itemType: 'Character', rarity: 4 },
  { englishName: 'yanfei', russianName: 'Янь Фэй', game: 'GENSHIN', itemType: 'Character', rarity: 4 },
  { englishName: 'yaoyao', russianName: 'Яо Яо', game: 'GENSHIN', itemType: 'Character', rarity: 4 },
  { englishName: 'yun jin', russianName: 'Юнь Цзинь', game: 'GENSHIN', itemType: 'Character', rarity: 4 },
  { englishName: 'zhongli', russianName: 'Чжун Ли', game: 'GENSHIN', itemType: 'Character', rarity: 5 },

  // Weapons
  { englishName: 'amos bow', russianName: 'Лук Амоса', game: 'GENSHIN', itemType: 'Weapon', rarity: 5 },
  { englishName: 'aquila favonia', russianName: 'Аквила Фавония', game: 'GENSHIN', itemType: 'Weapon', rarity: 5 },
  { englishName: 'black tassel', russianName: 'Чёрная кисточка', game: 'GENSHIN', itemType: 'Weapon', rarity: 3 },
  { englishName: 'bloodtainted greatsword', russianName: 'Окровавленный великий меч', game: 'GENSHIN', itemType: 'Weapon', rarity: 3 },
  { englishName: 'calamity queller', russianName: 'Усмиритель бед', game: 'GENSHIN', itemType: 'Weapon', rarity: 5 },
  { englishName: 'cool steel', russianName: 'Холодная сталь', game: 'GENSHIN', itemType: 'Weapon', rarity: 3 },
  { englishName: 'debate club', russianName: 'Дубина для споров', game: 'GENSHIN', itemType: 'Weapon', rarity: 3 },
  { englishName: 'dragons bane', russianName: 'Проклятие дракона', game: 'GENSHIN', itemType: 'Weapon', rarity: 4 },
  { englishName: 'emerald orb', russianName: 'Изумрудный шар', game: 'GENSHIN', itemType: 'Weapon', rarity: 3 },
  { englishName: 'eye of perception', russianName: 'Око восприятия', game: 'GENSHIN', itemType: 'Weapon', rarity: 4 },
  { englishName: 'favonius codex', russianName: 'Кодекс Фавония', game: 'GENSHIN', itemType: 'Weapon', rarity: 4 },
  { englishName: 'favonius greatsword', russianName: 'Великий меч Фавония', game: 'GENSHIN', itemType: 'Weapon', rarity: 4 },
  { englishName: 'favonius lance', russianName: 'Копьё Фавония', game: 'GENSHIN', itemType: 'Weapon', rarity: 4 },
  { englishName: 'favonius sword', russianName: 'Меч Фавония', game: 'GENSHIN', itemType: 'Weapon', rarity: 4 },
  { englishName: 'favonius warbow', russianName: 'Лук Фавония', game: 'GENSHIN', itemType: 'Weapon', rarity: 4 },
  { englishName: 'ferrous shadow', russianName: 'Железная тень', game: 'GENSHIN', itemType: 'Weapon', rarity: 3 },
  { englishName: 'flowerwreathed feathers', russianName: 'Цветочные перья', game: 'GENSHIN', itemType: 'Weapon', rarity: 4 },
  { englishName: 'harbinger of dawn', russianName: 'Предвестник зари', game: 'GENSHIN', itemType: 'Weapon', rarity: 3 },
  { englishName: 'key of khajnisut', russianName: 'Ключ Кхадж-нисут', game: 'GENSHIN', itemType: 'Weapon', rarity: 5 },
  { englishName: 'lions roar', russianName: 'Рык льва', game: 'GENSHIN', itemType: 'Weapon', rarity: 4 },
  { englishName: 'lithic spear', russianName: 'Каменное копьё', game: 'GENSHIN', itemType: 'Weapon', rarity: 4 },
  { englishName: 'magic guide', russianName: 'Руководство по магии', game: 'GENSHIN', itemType: 'Weapon', rarity: 3 },
  { englishName: 'mistsplitter reforged', russianName: 'Рассекающий туман', game: 'GENSHIN', itemType: 'Weapon', rarity: 5 },
  { englishName: 'mitternachts waltz', russianName: 'Вальс полуночи', game: 'GENSHIN', itemType: 'Weapon', rarity: 4 },
  { englishName: 'mountainbracing bolt', russianName: 'Горный болт', game: 'GENSHIN', itemType: 'Weapon', rarity: 4 },
  { englishName: 'mouuns moon', russianName: 'Луна Моун', game: 'GENSHIN', itemType: 'Weapon', rarity: 4 },
  { englishName: 'peak patrol song', russianName: 'Песнь патруля пика', game: 'GENSHIN', itemType: 'Weapon', rarity: 4 },
  { englishName: 'primordial jade wingedspear', russianName: 'Нефритовое крылатое копьё', game: 'GENSHIN', itemType: 'Weapon', rarity: 5 },
  { englishName: 'rainslasher', russianName: 'Дождерез', game: 'GENSHIN', itemType: 'Weapon', rarity: 4 },
  { englishName: 'raven bow', russianName: 'Вороний лук', game: 'GENSHIN', itemType: 'Weapon', rarity: 3 },
  { englishName: 'redhorn stonethresher', russianName: 'Красный рог - камнерез', game: 'GENSHIN', itemType: 'Weapon', rarity: 5 },
  { englishName: 'rust', russianName: 'Ржавчина', game: 'GENSHIN', itemType: 'Weapon', rarity: 4 },
  { englishName: 'sacrificial bow', russianName: 'Жертвенный лук', game: 'GENSHIN', itemType: 'Weapon', rarity: 4 },
  { englishName: 'sacrificial fragments', russianName: 'Жертвенные фрагменты', game: 'GENSHIN', itemType: 'Weapon', rarity: 4 },
  { englishName: 'sacrificial greatsword', russianName: 'Жертвенный великий меч', game: 'GENSHIN', itemType: 'Weapon', rarity: 4 },
  { englishName: 'sacrificial sword', russianName: 'Жертвенный меч', game: 'GENSHIN', itemType: 'Weapon', rarity: 4 },
  { englishName: 'sharpshooters oath', russianName: 'Клятва стрелка', game: 'GENSHIN', itemType: 'Weapon', rarity: 3 },
  { englishName: 'skyrider sword', russianName: 'Меч небесного всадника', game: 'GENSHIN', itemType: 'Weapon', rarity: 3 },
  { englishName: 'skyward blade', russianName: 'Небесный клинок', game: 'GENSHIN', itemType: 'Weapon', rarity: 5 },
  { englishName: 'skyward pride', russianName: 'Небесная гордость', game: 'GENSHIN', itemType: 'Weapon', rarity: 5 },
  { englishName: 'skyward spine', russianName: 'Небесный хребет', game: 'GENSHIN', itemType: 'Weapon', rarity: 5 },
  { englishName: 'slingshot', russianName: 'Рогатка', game: 'GENSHIN', itemType: 'Weapon', rarity: 3 },
  { englishName: 'sturdy bone', russianName: 'Крепкая кость', game: 'GENSHIN', itemType: 'Weapon', rarity: 4 },
  { englishName: 'the bell', russianName: 'Колокол', game: 'GENSHIN', itemType: 'Weapon', rarity: 4 },
  { englishName: 'the dockhands assistant', russianName: 'Помощник докера', game: 'GENSHIN', itemType: 'Weapon', rarity: 4 },
  { englishName: 'the flute', russianName: 'Флейта', game: 'GENSHIN', itemType: 'Weapon', rarity: 4 },
  { englishName: 'the stringless', russianName: 'Безгласная', game: 'GENSHIN', itemType: 'Weapon', rarity: 4 },
  { englishName: 'the widsith', russianName: 'Власть и мудрость', game: 'GENSHIN', itemType: 'Weapon', rarity: 4 },
  { englishName: 'thrilling tales of dragon slayers', russianName: 'Увлекательные истории о драконоубийцах', game: 'GENSHIN', itemType: 'Weapon', rarity: 3 },
  { englishName: 'tome of the eternal flow', russianName: 'Том вечного потока', game: 'GENSHIN', itemType: 'Weapon', rarity: 5 },
  { englishName: 'uraku misugiri', russianName: 'Ураку Мисугири', game: 'GENSHIN', itemType: 'Weapon', rarity: 5 },
  { englishName: 'wavebreakers fin', russianName: 'Плавник волнолома', game: 'GENSHIN', itemType: 'Weapon', rarity: 4 },
  { englishName: 'wine and song', russianName: 'Вино и песнь', game: 'GENSHIN', itemType: 'Weapon', rarity: 4 },
  { englishName: 'wolfs gravestone', russianName: 'Волчья могила', game: 'GENSHIN', itemType: 'Weapon', rarity: 5 },
  { englishName: 'xiphos moonlight', russianName: 'Лунный свет Ксифоса', game: 'GENSHIN', itemType: 'Weapon', rarity: 4 }
]

async function importExistingMappings() {
  console.log('📥 Импорт существующих маппингов в новую таблицу...')

  try {
    // Очищаем таблицу
    await prisma.itemNameMapping.deleteMany()
    console.log('🧹 Таблица очищена')

    // Добавляем маппинги порциями
    const batchSize = 20
    let importedCount = 0

    for (let i = 0; i < existingMappings.length; i += batchSize) {
      const batch = existingMappings.slice(i, i + batchSize)
      
      await prisma.itemNameMapping.createMany({
        data: batch,
        skipDuplicates: true
      })

      importedCount += batch.length
      console.log(`📦 Импортировано ${importedCount}/${existingMappings.length} маппингов...`)
    }

    console.log(`✅ Импорт завершён! Всего добавлено: ${importedCount} маппингов`)

    // Показать статистику
    const stats = await prisma.itemNameMapping.groupBy({
      by: ['game', 'itemType'],
      _count: {
        id: true
      },
      orderBy: [
        { game: 'asc' },
        { itemType: 'asc' }
      ]
    })

    console.log('\n📊 Статистика импорта:')
    stats.forEach(stat => {
      console.log(`   ${stat.game} ${stat.itemType}: ${stat._count.id} предметов`)
    })

  } catch (error) {
    console.error('❌ Ошибка импорта:', error)
  } finally {
    await prisma.$disconnect()
  }
}

importExistingMappings()
